#pragma once
#pragma push_macro("assert")

// C++
#include <array>
#include <atomic>
#include <charconv>
#include <coroutine>
#include <cmath>
#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <exception>
#include <filesystem>
#include <forward_list>
#include <functional>
#include <iostream>
#include <memory>
#include <mutex>
#include <numbers>
#include <ostream>
#include <random>
#include <shared_mutex>
#include <sstream>
#include <stop_token>
#include <string>
#include <string_view>
#include <thread>
#include <type_traits>
#include <typeindex>
#include <typeinfo>
#include <unordered_map>
#include <unordered_set>
#include <vector>

// Windows
#include <Windows.h>
#include <ShlObj.h>
#include <wrl.h>

#pragma pop_macro("assert")
