#pragma once

#include "../source/ff.base.c/pch.h"

#include "../source/ff.base.c/app/app.h"

#include "../source/ff.base.c/base/arena.h"
#include "../source/ff.base.c/base/array.h"
#include "../source/ff.base.c/base/assert.h"
#include "../source/ff.base.c/base/hash.h"
#include "../source/ff.base.c/base/log.h"
#include "../source/ff.base.c/base/math.h"
#include "../source/ff.base.c/base/point.h"
#include "../source/ff.base.c/base/rect.h"
#include "../source/ff.base.c/base/signal.h"
#include "../source/ff.base.c/base/span.h"
#include "../source/ff.base.c/base/string.h"
#include "../source/ff.base.c/base/string_builder.h"

#include "../source/ff.base.c/data/compression.h"
#include "../source/ff.base.c/data/dict.h"
#include "../source/ff.base.c/data/file.h"
#include "../source/ff.base.c/data/idict.h"
#include "../source/ff.base.c/data/json.h"
#include "../source/ff.base.c/data/png.h"
#include "../source/ff.base.c/data/settings.h"
#include "../source/ff.base.c/data/stream.h"
#include "../source/ff.base.c/data/value.h"
#include "../source/ff.base.c/data/value_type.h"

#include "../source/ff.base.c/dx12/dx12_agility.h"
#include "../source/ff.base.c/dx12/dx12_color.h"
#include "../source/ff.base.c/dx12/dx12_descriptor_allocator.h"
#include "../source/ff.base.c/dx12/dx12_descriptor_range.h"
#include "../source/ff.base.c/dx12/dx12_format.h"
#include "../source/ff.base.c/dx12/dx12_device_child.h"
#include "../source/ff.base.c/dx12/dx12_fence.h"
#include "../source/ff.base.c/dx12/dx12_fence_values.h"
#include "../source/ff.base.c/dx12/dx12_gpu_event.h"
#include "../source/ff.base.c/dx12/dx12_globals.h"
#include "../source/ff.base.c/dx12/dx12_heap.h"
#include "../source/ff.base.c/dx12/dx12_mem_allocator.h"
#include "../source/ff.base.c/dx12/dx12_matrix.h"
#include "../source/ff.base.c/dx12/dx12_mem_range.h"
#include "../source/ff.base.c/dx12/dx12_residency.h"
#include "../source/ff.base.c/dx12/dx12_resource_state.h"
#include "../source/ff.base.c/dx12/dx12_resource_tracker.h"
#include "../source/ff.base.c/dx12/dx12_resource.h"
#include "../source/ff.base.c/dx12/dx12_pacing.h"
#include "../source/ff.base.c/dx12/dx12_queue.h"
#include "../source/ff.base.c/dx12/dx12_commands.h"
#include "../source/ff.base.c/dx12/dx12_object_cache.h"
#include "../source/ff.base.c/dx12/dx12_buffer.h"
#include "../source/ff.base.c/dx12/dx12_texture.h"
#include "../source/ff.base.c/dx12/dx12_texture_view.h"
#include "../source/ff.base.c/dx12/dx12_depth.h"
#include "../source/ff.base.c/dx12/dx12_target_texture.h"
#include "../source/ff.base.c/dx12/dx12_target_window.h"
#include "../source/ff.base.c/dx12/dx12_reset.h"

#include "../source/ff.base.c/windows/module.h"
#include "../source/ff.base.c/windows/task.h"
#include "../source/ff.base.c/windows/dispatch.h"
#include "../source/ff.base.c/windows/window.h"
