#pragma once

#include "../source/ff.dx/pch.h"
#include "../source/ff.dx/init.h"

#include "../source/ff.dx/audio/audio.h"
#include "../source/ff.dx/audio/audio_child_base.h"
#include "../source/ff.dx/audio/audio_effect.h"
#include "../source/ff.dx/audio/audio_effect_base.h"
#include "../source/ff.dx/audio/audio_effect_playing.h"
#include "../source/ff.dx/audio/audio_playing_base.h"
#include "../source/ff.dx/audio/destroy_voice.h"
#include "../source/ff.dx/audio/music.h"
#include "../source/ff.dx/audio/music_playing.h"
#include "../source/ff.dx/audio/wav_file.h"

#include "../source/ff.dx/input/gamepad_device.h"
#include "../source/ff.dx/input/input.h"
#include "../source/ff.dx/input/input_device_base.h"
#include "../source/ff.dx/input/input_device_event.h"
#include "../source/ff.dx/input/input_mapping.h"
#include "../source/ff.dx/input/input_vk.h"
#include "../source/ff.dx/input/keyboard_device.h"
#include "../source/ff.dx/input/pointer_device.h"

#include "../source/ff.dx/dxgi/buffer_base.h"
#include "../source/ff.dx/dxgi/color.h"
#include "../source/ff.dx/dxgi/command_context_base.h"
#include "../source/ff.dx/dxgi/data_blob.h"
#include "../source/ff.dx/dxgi/depth_base.h"
#include "../source/ff.dx/dxgi/device_child_base.h"
#include "../source/ff.dx/dxgi/draw_base.h"
#include "../source/ff.dx/dxgi/draw_device_base.h"
#include "../source/ff.dx/dxgi/draw_ptr.h"
#include "../source/ff.dx/dxgi/draw_util.h"
#include "../source/ff.dx/dxgi/format_util.h"
#include "../source/ff.dx/dxgi/interop.h"
#include "../source/ff.dx/dxgi/intrusive_list.h"
#include "../source/ff.dx/dxgi/matrix.h"
#include "../source/ff.dx/dxgi/matrix_stack.h"
#include "../source/ff.dx/dxgi/operators.h"
#include "../source/ff.dx/dxgi/palette_base.h"
#include "../source/ff.dx/dxgi/palette_data_base.h"
#include "../source/ff.dx/dxgi/sprite_data.h"
#include "../source/ff.dx/dxgi/sprite_type.h"
#include "../source/ff.dx/dxgi/target_access_base.h"
#include "../source/ff.dx/dxgi/target_base.h"
#include "../source/ff.dx/dxgi/target_window_base.h"
#include "../source/ff.dx/dxgi/texture_base.h"
#include "../source/ff.dx/dxgi/texture_metadata_base.h"
#include "../source/ff.dx/dxgi/texture_util.h"
#include "../source/ff.dx/dxgi/texture_view_access_base.h"
#include "../source/ff.dx/dxgi/texture_view_base.h"
#include "../source/ff.dx/dxgi/transform.h"
#include "../source/ff.dx/dxgi/utility.h"
#include "../source/ff.dx/dxgi/vertex.h"

#include "../source/ff.dx/dx12/access.h"
#include "../source/ff.dx/dx12/buffer.h"
#include "../source/ff.dx/dx12/commands.h"
#include "../source/ff.dx/dx12/depth.h"
#include "../source/ff.dx/dx12/descriptor_allocator.h"
#include "../source/ff.dx/dx12/descriptor_range.h"
#include "../source/ff.dx/dx12/device_reset_priority.h"
#include "../source/ff.dx/dx12/draw_device.h"
#include "../source/ff.dx/dx12/fence.h"
#include "../source/ff.dx/dx12/fence_value.h"
#include "../source/ff.dx/dx12/fence_values.h"
#include "../source/ff.dx/dx12/globals.h"
#include "../source/ff.dx/dx12/gpu_event.h"
#include "../source/ff.dx/dx12/heap.h"
#include "../source/ff.dx/dx12/mem_allocator.h"
#include "../source/ff.dx/dx12/mem_range.h"
#include "../source/ff.dx/dx12/object_cache.h"
#include "../source/ff.dx/dx12/queue.h"
#include "../source/ff.dx/dx12/queues.h"
#include "../source/ff.dx/dx12/residency.h"
#include "../source/ff.dx/dx12/resource.h"
#include "../source/ff.dx/dx12/resource_state.h"
#include "../source/ff.dx/dx12/resource_tracker.h"
#include "../source/ff.dx/dx12/target_access.h"
#include "../source/ff.dx/dx12/target_texture.h"
#include "../source/ff.dx/dx12/target_window.h"
#include "../source/ff.dx/dx12/texture.h"
#include "../source/ff.dx/dx12/texture_util12.h"
#include "../source/ff.dx/dx12/texture_view.h"
#include "../source/ff.dx/dx12/texture_view_access.h"

#include "../source/ff.dx/graphics/animation.h"
#include "../source/ff.dx/graphics/animation_base.h"
#include "../source/ff.dx/graphics/animation_keys.h"
#include "../source/ff.dx/graphics/animation_player.h"
#include "../source/ff.dx/graphics/animation_player_base.h"
#include "../source/ff.dx/graphics/font_file.h"
#include "../source/ff.dx/graphics/graphics.h"
#include "../source/ff.dx/graphics/palette_cycle.h"
#include "../source/ff.dx/graphics/palette_data.h"
#include "../source/ff.dx/graphics/png_image.h"
#include "../source/ff.dx/graphics/random_sprite.h"
#include "../source/ff.dx/graphics/render_targets.h"
#include "../source/ff.dx/graphics/shader.h"
#include "../source/ff.dx/graphics/sprite.h"
#include "../source/ff.dx/graphics/sprite_base.h"
#include "../source/ff.dx/graphics/sprite_font.h"
#include "../source/ff.dx/graphics/sprite_list.h"
#include "../source/ff.dx/graphics/sprite_optimizer.h"
#include "../source/ff.dx/graphics/sprite_resource.h"
#include "../source/ff.dx/graphics/texture_data.h"
#include "../source/ff.dx/graphics/texture_metadata.h"
#include "../source/ff.dx/graphics/texture_resource.h"
#include "../source/ff.dx/graphics/viewport.h"

#pragma comment(lib, "d3d12.lib")
#pragma comment(lib, "d3dcompiler.lib")
#pragma comment(lib, "dwrite.lib")
#pragma comment(lib, "dxgi.lib")
#pragma comment(lib, "Mfplat.lib")
#pragma comment(lib, "Mfreadwrite.lib")
#pragma comment(lib, "Mfuuid.lib")
#pragma comment(lib, "Xinput.lib")

#if PROFILE_APP
#pragma comment(lib, "WinPixEventRuntime.lib")
#endif
