#pragma once

#include "../source/ff.dx/pch.h"
#include "../source/ff.dx/audio/audio.h"
#include "../source/ff.dx/audio/audio_child_base.h"
#include "../source/ff.dx/audio/audio_effect.h"
#include "../source/ff.dx/audio/audio_effect_base.h"
#include "../source/ff.dx/audio/audio_effect_playing.h"
#include "../source/ff.dx/audio/audio_playing_base.h"
#include "../source/ff.dx/audio/destroy_voice.h"
#include "../source/ff.dx/audio/music.h"
#include "../source/ff.dx/audio/music_playing.h"
#include "../source/ff.dx/audio/wav_file.h"
#include "../source/ff.dx/init.h"
#include "../source/ff.dx/input/gamepad_device.h"
#include "../source/ff.dx/input/input.h"
#include "../source/ff.dx/input/input_device_base.h"
#include "../source/ff.dx/input/input_device_event.h"
#include "../source/ff.dx/input/input_mapping.h"
#include "../source/ff.dx/input/input_vk.h"
#include "../source/ff.dx/input/keyboard_device.h"
#include "../source/ff.dx/input/pointer_device.h"

#include "../source/ff.dx/dxgi/buffer_base.h"
#include "../source/ff.dx/dxgi/color.h"
#include "../source/ff.dx/dxgi/command_context_base.h"
#include "../source/ff.dx/dxgi/data_blob.h"
#include "../source/ff.dx/dxgi/depth_base.h"
#include "../source/ff.dx/dxgi/device_child_base.h"
#include "../source/ff.dx/dxgi/draw_base.h"
#include "../source/ff.dx/dxgi/draw_device_base.h"
#include "../source/ff.dx/dxgi/draw_ptr.h"
#include "../source/ff.dx/dxgi/draw_util.h"
#include "../source/ff.dx/dxgi/format_util.h"
#include "../source/ff.dx/dxgi/interop.h"
#include "../source/ff.dx/dxgi/intrusive_list.h"
#include "../source/ff.dx/dxgi/matrix.h"
#include "../source/ff.dx/dxgi/matrix_stack.h"
#include "../source/ff.dx/dxgi/operators.h"
#include "../source/ff.dx/dxgi/palette_base.h"
#include "../source/ff.dx/dxgi/palette_data_base.h"
#include "../source/ff.dx/dxgi/sprite_data.h"
#include "../source/ff.dx/dxgi/sprite_type.h"
#include "../source/ff.dx/dxgi/target_access_base.h"
#include "../source/ff.dx/dxgi/target_base.h"
#include "../source/ff.dx/dxgi/target_window_base.h"
#include "../source/ff.dx/dxgi/texture_base.h"
#include "../source/ff.dx/dxgi/texture_metadata_base.h"
#include "../source/ff.dx/dxgi/texture_util.h"
#include "../source/ff.dx/dxgi/texture_view_access_base.h"
#include "../source/ff.dx/dxgi/texture_view_base.h"
#include "../source/ff.dx/dxgi/transform.h"
#include "../source/ff.dx/dxgi/utility.h"
#include "../source/ff.dx/dxgi/vertex.h"

#pragma comment(lib, "Mfplat.lib")
#pragma comment(lib, "Mfreadwrite.lib")
#pragma comment(lib, "Mfuuid.lib")
#pragma comment(lib, "Xinput.lib")
