#pragma once

#include "../source/ff.dxgi/pch.h"
#include "../source/ff.dxgi/source/buffer_base.h"
#include "../source/ff.dxgi/source/color.h"
#include "../source/ff.dxgi/source/command_context_base.h"
#include "../source/ff.dxgi/source/data_blob.h"
#include "../source/ff.dxgi/source/depth_base.h"
#include "../source/ff.dxgi/source/device_child_base.h"
#include "../source/ff.dxgi/source/draw_base.h"
#include "../source/ff.dxgi/source/draw_device_base.h"
#include "../source/ff.dxgi/source/draw_ptr.h"
#include "../source/ff.dxgi/source/draw_util.h"
#include "../source/ff.dxgi/source/format_util.h"
#include "../source/ff.dxgi/source/interop.h"
#include "../source/ff.dxgi/source/intrusive_list.h"
#include "../source/ff.dxgi/source/matrix.h"
#include "../source/ff.dxgi/source/matrix_stack.h"
#include "../source/ff.dxgi/source/operators.h"
#include "../source/ff.dxgi/source/palette_base.h"
#include "../source/ff.dxgi/source/palette_data_base.h"
#include "../source/ff.dxgi/source/sprite_data.h"
#include "../source/ff.dxgi/source/sprite_type.h"
#include "../source/ff.dxgi/source/target_access_base.h"
#include "../source/ff.dxgi/source/target_base.h"
#include "../source/ff.dxgi/source/target_window_base.h"
#include "../source/ff.dxgi/source/texture_base.h"
#include "../source/ff.dxgi/source/texture_metadata_base.h"
#include "../source/ff.dxgi/source/texture_util.h"
#include "../source/ff.dxgi/source/texture_view_access_base.h"
#include "../source/ff.dxgi/source/texture_view_base.h"
#include "../source/ff.dxgi/source/transform.h"
#include "../source/ff.dxgi/source/utility.h"
#include "../source/ff.dxgi/source/vertex.h"

#pragma comment(lib, "dxgi.lib")
