#pragma once

#include "pch.h"
#include "source/auto_resource.h"
#include "source/file_o.h"
#include "source/init.h"
#include "source/resource.h"
#include "source/resource_load.h"
#include "source/resource_load_context.h"
#include "source/resource_object_base.h"
#include "source/resource_object_factory_base.h"
#include "source/resource_object_provider.h"
#include "source/resource_object_v.h"
#include "source/resource_objects.h"
#include "source/resource_value_provider.h"
#include "source/resource_values.h"
#include "source/resource_v.h"
